version: "3.6"

services:
  postgresql:
    image: postgres:17.4-alpine3.21
    container_name: postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopping
    ports:
      - 5432:5432

  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    ports:
      - 6379:6379
