
name: "Release"

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Version of the app to be released"
      deploy_on_success:
        type: boolean
        default: false
        description: "Automatic deployment on success"

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  docker-release:
    needs: tests
    uses: sylvanld/github-workflows/.github/workflows/docker-release.yml@v1
    secrets: inherit
    with:
      docker_image_name: sylvanld/shopping-api
      docker_image_tags: ${{ inputs.version }}

  git-release:
    needs: docker-release
    uses: sylvanld/github-workflows/.github/workflows/git-tag.yml@v1
    with:
      git_tag: ${{ inputs.version }}
  
  deploy:
    needs: git-release
    if: inputs.deploy_on_success
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
