name: "Run tests"

on:
  push:
    branches:
      - "*"

jobs:
  python-tests:
    uses: sylvanld/github-workflows/.github/workflows/python-tests.yml@main
    with:
      python_version: "3.10"
      requirements_file: "requirements/dev.txt"
      source_directory: "shopping/"
      pytest_enabled: true
      linting_enabled: true
