name: "Run tests"

on:
  workflow_call:
  push:
    branches:
      - "*"

jobs:
  helm-tests:
    uses: sylvanld/github-workflows/.github/workflows/helm-tests.yml@v1
    with:
      helm_version: "v3.9.2"
      helm_chart_path: "chart/"
  
  python-tests:
    uses: sylvanld/github-workflows/.github/workflows/python-tests.yml@v1
    with:
      python_version: "3.10"
      requirements_file: "requirements/dev.txt"
      source_directory: "shopping/"
      pytest_enabled: true
      linting_enabled: true
